variables:
  PROJECT_NAME: sport-news-stub

  IMAGE_NAME: $PROJECT_NAME
  # IMAGE_NAME_NGINX: -- переменная для имени образа nginx
  # CONTAINER_PORT[_SMTH] - Порт, доступный снаружи
  # LISTEN_PORT[_SMTH] - Порт, который слушает контейнер изнутри
  # Переменные с перфиксом CDEV используются на деве
  # Переменные с префиксом PROD используются на проде
  CDEV_CONTAINER_PORT: 3029
    
  PROD_CONTAINER_PORT: 3023

  CDEV_LOG_PATH: /1/log/nginx/${PROJECT_NAME}

  PROD_LOG_PATH: /1/log/nginx/${PROJECT_NAME}

  
  LISTEN_PORT: 80


  TIMEZONE: 'Europe/Moscow'
  BUILD_TAG: $CI_COMMIT_SHORT_SHA
  PROJECT_TYPE: nodejs

include:
  - project: 'devops-and-administration/cicd-common'
    ref: 'master'
    file: '/frontend/v1/gitlab-ci-node-nginx-no-auto.yml'
  # if branch is not master deploy to cdev server
#  - project: 'devops-and-administration/cicd-common'
#    file: '/servers/cdev.yml'
#    ref: 'master'
#    rules:
#      - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  # if branch is master deploy to production server
  - project: 'devops-and-administration/cicd-common'
    file : '/servers/sport-news-stub.arboost.ru.yml'
    ref: 'master'
    rules:
      - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
